### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by camfindlay** [GOVTNZ/web-standards#1]
+1 for using Jekyll and GH-Pages :+1:

**Comment by jasonkiss** [comment]
Thanks. We're still figuring out how we're going to manage our use of them, but for the time being GH and gh-pages are useful for openly sharing and collaborating on the standards and guidance we're developing.

**Comment by camfindlay** [comment]
Would be great to have the source material for web tool kit guidance as markdown... then other could contribute and improve more effectively.

**Comment by jasonkiss** [comment]
Good suggestion. Will look into getting the authors onto that.

**Comment by jasonkiss** [comment]
FYI, converted to jekyll and markdown. Thanks for suggestion.
